### ISSUE TITLE
Facing Error in installing ubeR 

### ISSUE THREAD

**Issue by N1t1nA** [DataWookie/ubeR#5]
install.packages("devtools")
devtools::install_github("hadley/httr")
devtools::install_github("DataWookie/UbeR")

Facing Error 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'RgoogleMaps'
ERROR: lazy loading failed for package 'ubeR'
* removing 'C:/Users/nitinahu/Documents/R/win-library/3.3/ubeR'
Error: Command failed (1)

using the following R Version

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by datawookie** [comment]
Hi,

Thank you for your terse issue log.

It's difficult to know what happened given that you have only provided the final portion of the install log. However, I am going to hypothesize that you are working on Windows machine and that the explicit dependencies in ubeR are being installed from .zip archives. It seems that these do not handle their own dependencies very well and, consequently, ggmap which has a dependency on RgoogleMaps breaks.

I'd suggest that you try

```
install.packages("ggmap")
devtools::install_github("DataWookie/UbeR")
```

Let me know how that goes.

Regards,
Andrew.

**Comment by N1t1nA** [comment]
Thanks @DataWookie, this solves my problem of loading library UbeR
Thanks again for quick response.
