### ISSUE TITLE
uber_estimate_price

### ISSUE THREAD

**Issue by ghost** [DataWookie/ubeR#7]
Hi, 
The "uber_estimate_price" function returns an estimated price range for each Uber product offered at given location. Can I use it iteratively so as to create a data frame that contains price estimates for a given set of locations?  This is the specific issue I have:
I have the following data frame that contains just three possible travels that a user could take with Uber in Bogotá city. 

places <- data.frame(From = c("Terminal Norte", "Calle 187", "Portal del Norte"), latitude_origin=c(4.7688914, 4.762931, 4.7542353), longitude_origin=c(-74.0435571, -74.044235, -74.0483541), To = c("CC Atlantis Plaza", "Aeropuerto", "Unicentro"), latitude_destination=c(4.66597, 4.6970364, 4.7026557), longitude_destination = c(-74.05558, -74.1417301, -74.0436772))

I could use the function  for getting a range of uber prices for the first row of this data frame, like this:
price <- uber_estimate_price(place$latitude_origin[1], place$longitude_origin[1], place$latitude_destination[1], place$longitude_destination[1])
...and it works pretty well...

Now, I would like to use my "places" data set inside a loop so as to create a second data frame with the resulting prices for all the addresses  in my "places" data frame... 

 for (i in 1:nrow(places)){
  price <- uber_estimate_price(place$latitude_origin[i], place$longitude_origin[i], place$latitude_destination[i], place$longitude_destination[i])
}

 But the resulting "price" object is NULL

Any idea...

**Comment by ghost** [comment]
Oh, I forgot to provide my sessionInfo details... here you have....
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_CO.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=es_CO.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_CO.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_CO.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ubeR_0.1.4  readr_1.1.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11      magrittr_1.5      maps_3.1.1        hms_0.3          
 [5] munsell_0.4.2     colorspace_1.2-4  geosphere_1.5-5   lattice_0.20-33  
 [9] rjson_0.2.15      R6_2.2.1          jpeg_0.1-8        rlang_0.1.1      
[13] httr_1.2.1        stringr_1.2.0     plyr_1.8.4        dplyr_0.5.0      
[17] tools_3.3.1       grid_3.3.1        gtable_0.2.0      png_0.1-7        
[21] DBI_0.6-1         openssl_0.9.6     lazyeval_0.2.0    assertthat_0.2.0 
[25] tibble_1.3.3      ggmap_2.6.1       reshape2_1.4      mapproj_1.2-4    
[29] ggplot2_2.2.1     curl_2.6          sp_1.2-4          stringi_1.1.5    
[33] RgoogleMaps_1.4.1 scales_0.4.1      jsonlite_1.5      httpuv_1.3.3     
[37] proto_0.3-10

**Comment by datawookie** [comment]
Hi Juan,

I'm not sure that the code you provided would actually work since you name your data frame of locations `places` but use another variable named `place` in your call to `uber_estimate_price()`. But I get the idea of what you are trying to do.

This sounds more like a general R programming issue that something specific to the ubeR package, but let me see if I can help out.

I'll be back in a moment.

Regards,
Andrew.

**Comment by datawookie** [comment]
Here you go:

```
places <- data.frame(
  start_address = c("Terminal Norte", "Calle 187", "Portal del Norte"),
  start_latitude=c(4.7688914, 4.762931, 4.7542353),
  start_longitude=c(-74.0435571, -74.044235, -74.0483541), 
  end_address = c("CC Atlantis Plaza", "Aeropuerto", "Unicentro"),
  end_latitude=c(4.66597, 4.6970364, 4.7026557), 
  end_longitude = c(-74.05558, -74.1417301, -74.0436772)
  )

library(purrr)
library(dplyr)

places %>%
  select(start_latitude, start_longitude, end_latitude, end_longitude) %>%
  pmap(uber_estimate_price)
```

I renamed the columns in your data frame to make them consistent with the argument names to `uber_estimate_price()`. Then used `pmap()` from the `purrr` package to generate price information for each start/end pair. The result is returned as a list with as many elements as there are rows in the original data frame.

**Comment by jcorrean** [comment]
Thank you so much, Andrew. It worked nicely!

**Comment by datawookie** [comment]
Great. Happy to hear it. I'd be really interested to know how you are using this package. It's great to know that people are finding it useful.
